### ISSUE TITLE
Fix script for creating launch files

### ISSUE THREAD

**Issue by tik0** [tik0/amiro_potential_field_navigation#3]
The script cannot handle the following issues:

- Only one AMiRo is specified for demonstration
- Only one image_selector_node is specified
- The tracker topic is always the same: Something like '/artoolkit5_cam3_2......'

**Comment by dlindemann0** [comment]
Done. 
https://github.com/tik0/amiro_potential_field_navigation/commit/e9aa0e56b800e89443bb07b73f8241ad633f09d9
https://github.com/tik0/amiro_potential_field_navigation/commit/ca847d469af6b75fad7abc5180c93e938a129d90

**Comment by dlindemann0** [comment]
Tested. 
https://github.com/tik0/amiro_potential_field_navigation/commit/9319c6ae46cfa3b5bb31416a188b9f262d5f8a64
